### ISSUE TITLE
The version of this in `normalize-package-data` emits a warning for conflicts with core modules

### ISSUE THREAD

**Issue by iarna** [npm/validate-npm-package-name#1]
Specifically:
```js
 if (coreModuleNames.indexOf(data.name) !== -1)
      this.warn("conflictingName", data.name)
```

Using [this list](https://github.com/npm/normalize-package-data/blob/master/lib/core_module_names.json).

I'm not saying we *should* warn here, but I'd like to have that discussion.

**Comment by zeke** [comment]
https://www.npmjs.com/package/validate-npm-package-name 2.0 landed a few months back, with support for checking against core modules.
