### ISSUE TITLE
Inconsistent rules between scoped and non-scoped package names

### ISSUE THREAD

**Issue by nexdrew** [npm/validate-npm-package-name#10]
Here are examples:

| Example | Invalid | Valid | Rule/Category |
| --: | --- | --- | --- |
| 1 | `'.pkg'` | `'@scope/.pkg'` | name cannot start with a period |
| 2 | `'_pkg'` | `'@scope/_pkg'` | name cannot start with an underscore |
| 3 | `'node_modules'` | `'@scope/node_modules'` | blacklisted name |
| 4 | `'favicon.ico'` | `'@scope/favicon.ico'` | blacklisted name |
| 5 | `'fs'` | `'@scope/fs'` | core module name |

Not sure if any of these are actual problems (nothing really wrong with Example 5) but I wanted to create this issue for sake of awareness and discussion.

Note that these at least seem to be consistent with [logic in `normalize-package-data`](https://github.com/npm/normalize-package-data/blob/v2.3.5/lib/fixer.js#L314-L338), but I'm wondering why we duplicate this logic across multiple modules in different packages. Perhaps it would be better to centralize this logic here and add `validate-npm-package-name` as a dependency to `normalize-package-data`.

**Comment by billti** [comment]
I came to log the same bug. I'm actually more interest in if something like `@scope/_foo` is actually a valid package name. As if it is, that resolves a problem I'm facing. Thanks!

p.s. It does actually appear to publish fine. See my package at https://www.npmjs.com/package/@billti/_foo

**Comment by wraithgar** [comment]
This doesn't appear to have been an issue in the last 5 years.  Scoped package names are registry-specific and likely won't be something this module can filter if we want to support multiple registries.
