### ISSUE TITLE
[BUG] can't resolve `module` in browser

### ISSUE THREAD

**Issue by elrrrrrrr** [npm/validate-npm-package-name#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We've incorporated the `validate-npm-package-name` package in the frontend for format validation.

Since version 5.0.1 uses Node's built-in `module` to validate internal packages, this configuration is undefined in the browser environment.

Furthermore, no errors are reported during the build phase, leading to a breaking change.

This might be a bug caused by the bundler not handling `module` correctly. Considering that `validate-npm-package-name` is a very low-level dependency, would it be possible to revert to the previous method?

![image](https://github.com/npm/validate-npm-package-name/assets/5574625/80f9ede2-5a65-443b-84c4-1290a5000496)

### Expected Behavior

should work in browser

### Steps To Reproduce

[codesandbox](https://codesandbox.io/p/sandbox/antd-form-forked-nkk54k?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt6mhbwr00063b6f7r3jc3qp%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt6mhbwr00023b6fh9f93uva%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt6mhbwr00033b6f8cgh32dj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt6mhbwr00053b6fcp11yy2o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt6mhbwr00023b6fh9f93uva%2522%253A%257B%2522id%2522%253A%2522clt6mhbwr00023b6fh9f93uva%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt6minbe005m3b6f7q03542r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A3%252C%2522startColumn%2522%253A24%252C%2522endLineNumber%2522%253A3%252C%2522endColumn%2522%253A24%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clt6mk48g00023b6kr94iga6o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A29%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A29%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clt6mk48g00023b6kr94iga6o%2522%257D%252C%2522clt6mhbwr00053b6fcp11yy2o%2522%253A%257B%2522id%2522%253A%2522clt6mhbwr00053b6fcp11yy2o%2522%252C%2522activeTabId%2522%253A%2522clvxk5m1g00x63b6i5w8jgzr8%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clvxk5m1g00x63b6i5w8jgzr8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clt6mhbwr00033b6f8cgh32dj%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clt6mhbwr00033b6f8cgh32dj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

it seems that this issue cannot be directly reproduced in CodeSandbox due to not being able to sync to the latest version.

### Environment

- npm: 10
- Node: 20
- OS: mac
- platform: arm64

**Comment by wraithgar** [comment]
> This might be a bug caused by the bundler not handling module correctly.

This is correct.  This is a Node.js module.  Bundlers are responsible for making such modules work in the browser.

**Comment by kyletsang** [comment]
We just ran into this problem too and we'll need to pin to 5.0 for now.  Shouldn't this be considered a breaking change or was `validate-npm-package-name` not intended to be used in browsers?
