### ISSUE TITLE
[REQUEST] ES6 Usage / Browser Usage. 

### ISSUE THREAD

**Issue by MarketingPip** [npm/validate-npm-package-name#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It would be cool if we could use this for browser by using - https://www.npmjs.com/package/builtin-modules and auto update library on changes etc...

**Comment by wraithgar** [comment]
This is not something we are planning on doing right now

**Comment by MarketingPip** [comment]
> This is not something we are planning on doing right now

hmmm - since I needed to copy the code and replace builts etc - for something I'm doing. Could I possibly make a PR that solves this in a good way? (If I can craft a solution).
