### ISSUE TITLE
why is the maximum package name length 50 characters?

### ISSUE THREAD

**Issue by othiym23** [npm/validate-npm-package-name#4]
There's no rationale in the code or the commit history, and there are extant packages in the registry with names much longer than that, which is causing problems when the registry code is using `validate-npm-package-name` to validate new packages and returning 500 errors, e.g. npm/npm#8077 / npm/registry-frontdoor#133.

**Comment by zeke** [comment]
Hearsay was to blame for this restriction.. I have no objection to changing it.

**Comment by zeke** [comment]
At some point we had an in-air discussion where it was decided that `50` was a sensible max length for new package names. FWIW, this restriction is not applied to existing packages: https://github.com/npm/validate-npm-package-name/blob/69f5c629525feeccfc941a6f1b9280ceed8a4b3a/index.js#L61-L63

**Comment by wojciak** [comment]
That's a bummer. I namespace my packages so I have a:
mainLibrary
mainLibrary.components.
mainLibrary.plugins.
mainLibrary.plugins.somePlugin.with.optionalDependencies

This way I won't be able to use npm in a sensible way - as the organisation grows so does it's code base.

Also this will break the deal for anyone who'll want to name their packages like com.myOrganisation.packages.myVeryLongPackageNameBecauseIWorkedWithMVNYesterday.

Is there any reason to restrict the package length?
