### ISSUE TITLE
[BUG] TypeError: builtins is not a function

### ISSUE THREAD

**Issue by jorgebodega** [npm/validate-npm-package-name#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have an error on my github actions when trying to publish a package to NPM. I could not found any information about this, so I post the question here. If it shouldn't, please let me know.

The error is:

```
37 verbose stack TypeError: builtins is not a function
37 verbose stack     at validate (/home/runner/work/typeorm-seeding/typeorm-seeding/node_modules/npm/node_modules/npm-registry-fetch/node_modules/validate-npm-package-name/lib/index.js:55:3)
37 verbose stack     at Result.setName (/home/runner/work/typeorm-seeding/typeorm-seeding/node_modules/npm/node_modules/npm-registry-fetch/node_modules/npm-package-arg/lib/npa.js:127:17)
37 verbose stack     at new Result (/home/runner/work/typeorm-seeding/typeorm-seeding/node_modules/npm/node_modules/npm-registry-fetch/node_modules/npm-package-arg/lib/npa.js:119:10)
37 verbose stack     at Function.resolve (/home/runner/work/typeorm-seeding/typeorm-seeding/node_modules/npm/node_modules/npm-registry-fetch/node_modules/npm-package-arg/lib/npa.js:56:15)
37 verbose stack     at npa (/home/runner/work/typeorm-seeding/typeorm-seeding/node_modules/npm/node_modules/npm-registry-fetch/node_modules/npm-package-arg/lib/npa.js:26:18)
37 verbose stack     at Function.pickRegistry (/home/runner/work/typeorm-seeding/typeorm-seeding/node_modules/npm/node_modules/npm-registry-fetch/lib/index.js:189:10)
37 verbose stack     at Publish.exec (/home/runner/work/typeorm-seeding/typeorm-seeding/node_modules/npm/lib/commands/publish.js:107:33)
37 verbose stack     at async module.exports (/home/runner/work/typeorm-seeding/typeorm-seeding/node_modules/npm/lib/cli.js:66:5)
```

### Expected Behavior

It should not throw any error.

### Steps To Reproduce

You can go to [this repo](https://github.com/jorgebodega/typeorm-seeding/tree/next) at the point of failure.

Or you can go to [the action](https://github.com/jorgebodega/typeorm-seeding/actions/runs/2660027228) that is causing the problem.

Both places are visible, so it should be a good point to check the code.

### Environment

- npm: v8.5.3
- Node: v16.13.0
- OS: Ubuntu 20.04
- platform: Github runner

**Comment by wraithgar** [comment]
It looks like whatever is installing your dependencies might installing something other than the version of `builtins` that this module is expecting.  Did this start about 12 days ago? Looks like there were changes to your yarn.lock file that are related to these deps.

You can try using `npm install` instead and see if that works.  Or bring this up in a yarn issue thread.  This is not an issue w/ this module however, as `builtins` is properly declared as a dependency.

**Comment by wraithgar** [comment]
This should never be happening, fwiw, as npm ships its dependencies as bundled. This means that everything needed to run npm ships with npm.  yarn ignores bundled dependencies.

**Comment by jorgebodega** [comment]
Thanks! I'm going to try with yarn one more time, and if that doesn't work, I'll probably open this issue again in yarn.
