### ISSUE TITLE
Hyphen name

### ISSUE THREAD

**Issue by dy** [npm/validate-npm-package-name#9]
I guess package cannot start with hyphen as well.
At least, the name `-` validates successfully, but registering package with that name is impossible.

**Comment by slang800** [comment]
Based on the validation logic [here](https://github.com/npm/npm-registry-couchapp/blob/b31793881ff95c5bca5966a0a8bf8e5f7a801247/registry/modules.js#L93) (particularly `!n.match(/^[a-zA-Z0-9]/)`) I think you're right.

There's a kinda confusing notice in the couchapp repo readme that says:

> deprecation notice: as npm has scaled, the registry architecture has gradually migrated towards a complex distributed architecture, of which npm-registry-couchapp is only a small part. FOSS is an important part of npm, and over time we plan on exposing more APIs, and better documenting the existing API.

So my first inclination is to copy the additional rules in the function mentioned above over to this module, and then make a PR to use "validate-npm-package-name" directly in the couchapp to prevent it from diverging again in the future. However, that "FOSS is an important part of npm..." part seems to imply that there are some non-public parts of this system, so I can't be totally sure that the couchapp is where validation is being done.
